command_line_args:
    actor_lr: 0.0001
    alpha3: 0.8
    alpha_lr: 0.0003
    area_size: 4
    batch_size: 256
    collision_penalty: -200
    correction_cost_dist: 0.05
    cost: 10
    cost_agent_dist: 4
    cost_coeff: 10
    cost_dist_agent: 0.1
    cost_dist_obs: 0.05
    cost_obs_dist: 2
    critic_lr: 0.0003
    danger_penalty_coeff: 40
    debug: false
    env: DoubleIntegrator
    eval_epi: 100
    eval_interval: 40
    gamma: 0.99
    hidden_dims: !!python/tuple
    - 256
    - 256
    log_dir: ./logs
    lyapunov_loss_coeff: 0.4
    max_step: 256
    n_rays: 32
    name: null
    num_agents: 8
    obs: 8
    potential_obs_reward_coeff: 20
    reach_reward: 5.0
    reward_scale: 5
    rl_algo: MAGLAC
    save_interval: 50
    seed: 99
    start_timesteps: 3000
    steps: 1000
    success_reward: 100
    tau: 0.005
    tgt_reward_coeff: 100
    tgt_reward_high: 4
    tgt_reward_low: -0.1
    total_timesteps: 512000
    w_delta1: 5
    w_delta2: 2
    warning_dist2agent: 5
    warning_dist2obs: 4
env_params:
    correction_cost_dist: 0.05
    cost: 10
    cost_agent_dist: 4
    cost_coeff: 10
    cost_dist_agent: 0.1
    cost_dist_obs: 0.05
    cost_obs_dist: 2
    danger_penalty_coeff: 40
    potential_obs_reward_coeff: 20
    reach_reward: 5.0
    reward_scale: 5
    success_reward: 100
    tgt_reward_coeff: 100
    tgt_reward_high: 4
    tgt_reward_low: -0.1
    w_delta1: 5
    w_delta2: 2
    warning_dist2agent: 5
    warning_dist2obs: 4
